---
- name: Configure apache2/httpd based on OS flavour
  hosts: all
  become: yes

  tasks:

    - name: Install apache2 on Ubuntu servers
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install httpd on RedHat servers
      yum:
        name: httpd
        state: present
      when: ansible_distribution == "RedHat"

    - name: Edit the index.html file
      copy:
        content: "Intelliq"
        dest: /var/www/html/index.html

    - name: Restart apache2 on Ubuntu servers
      service:
        name: apache2
        state: restarted
      when: ansible_distribution == "Ubuntu"

    - name: Restart httpd on RedHat servers
      service:
        name: httpd
        state: restarted
      when: ansible_distribution == "RedHat"

    - name: Check apache2/httpd response on all servers
      uri:
        url: "{{ item }}"
        status_code: 200
      with_items:
        - http://172.31.27.116
        - http://172.31.22.45
        - http://172.31.15.126
