---
- name: Implementing loops
  hosts: all
  become: yes
  tasks:
    - name: Install/uninstall/upgrade s/w apps
      apt:
        name: "{{ item.a }}"
        state: "{{ item.b }}"
        update_cache: "{{ item.c }}"
      with_items:
        - { a: openjdk-17-jdk, b: present, c: no }
        - { a: maven, b: absent,  c: no }
        - { a: tree,  b: latest,  c: yes }
