- name: Copy tomcat file to servers
  hosts: all
  become: yes

  tasks:
    - name: Create tomcat directory
      file:
        path: /opt/tomcat/conf
        state: directory
        mode: '0755'

    - name: Copy tomcat-users.xml
      copy:
        src: tomcat-users.xml
        dest: /opt/tomcat/conf/tomcat-users.xml
