- hosts: all
  become: yes
  tasks:

    - name: Install tomcat10
      apt:
        name: tomcat10
        state: present
        update_cache: yes

    - name: Install tomcat10-admin
      apt:
        name: tomcat10-admin
        state: present

    - name: Copy customised tomcat-users.xml file
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat10/tomcat-users.xml

    - name: Change port of tomcat from 8080 to 9090
      replace:
        path: /etc/tomcat10/server.xml
        regexp: '8080'
        replace: '9090'

    - name: Restart tomcat
      service:
        name: tomcat10
        state: restarted

    - name: Pause for 40 seconds
      pause:
        seconds: 40

    - name: Check tomcat on server1
      uri:
        url: http://172.31.27.116:9090
        status_code: 200

    - name: Check tomcat on server2
      uri:
        url: http://172.31.22.45:9090
        status_code: 200
