---
- name: Create user using host variables
  hosts: server
  become: yes
  tasks:
    - name: Create user
      user:
        name: "{{ a }}"
        password: "{{ b }}"
        uid: "{{ c }}"
        home: "{{ d }}"
        comment: "{{ e }}"
        shell: "{{ f }}"

