- name: Install Docker on all servers
  hosts: all
  become: yes

  tasks:
    - name: Download Docker install script
      shell: curl -fsSL https://get.docker.com -o install-docker.sh

    - name: Run Docker install script
      shell: sh install-docker.sh
