- name: Error Handling in ansible
  hosts: all
  become: yes

  tasks:
    - block:
        - name: Install git using apt
          apt:
            name: git
            state: present
            update_cache: yes

      rescue:
        - name: Install git using yum
          yum:
            name: git
            state: present
